// <auto-generated />
namespace CustomerManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class DatabaseCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204012024398_DatabaseCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so5N101aLvP4iW2YXeT2WNz5Kj8siI2xe5+X5e6K28xCofWQ7pW5PCb32+s31KueuXa9+K2r3e+XXwQf00cu6WuV1e/0qP9d3z2YfpXfD9+52X7Svee+ge/pt2d7b+yh9sS7LbFLSB+dZ2eQfpatPH71uqzr/PF/mddbms5dZ2+b1Eu/mjL6S4dHq09tR4uHdnT1Q4m62XFZt1tJM9xDvoPmsqJsWvxpsX7c1cc5H6bPiXT57ni8v2rnF+IvsnfmEfv0o/WpZEKPRS229ziMj3Nz18+znqufTRVaUP/xuX86r5Tc7Wvl7c69P82ZaFythhp/Vvh/fdVLXl0VSEW1WEKsrXir++Dh/13bEUl55nbcd6SU14foQXTG2kh1FxnbrVNJd0UlGd90dUF6Pv8hWK6KTp8z0k/S1arLt1++vqRYC4+60iSgsi63tiTQEkanzLXVNmLLsPs3abJJh5k5mi16z2xHZdNaldVczOtKbN/B7+Fao1d3kdGA5Yj6j8S1I3/FQdaCE05DG1pdfT7MyqyM696Qq14vlkN7e9LanCn0g3se3h+V0mw/KfXp7SKqrfDD60e1hqOLxYehHt4cRqBEfUvBFH97ju5157jKVpzS0ZcfSdtl0k5B3m9jerbB3hPqxCtgt3JauxEmTj1Ii1GUxg7S9vm7afDFGg/HrX1SelAWN1zUg0SjO86Z9U73N4YKRQvj6Xo+19U0zK//f6voUGP6NTs57mtGey7K8zOrpPKu3Ftm7O+8NruuGfBi0wLX4MFCBuzAI6mu6AO8B7/3Met8wDRidLnNuMuwiap99NJtUNABB1HMJvqbd74v+47t+XPOY6FZcOBCIcpb5FGR0QE2bs+V5ZchOo/MxMk06s/JF3mYzItJx3Rbn2bSlr6d507Bn9pNZuWZumuSzs+WX63a1bo+bJl9Mymt/vI/vbu6fnZsQ58dfMiN4uu7rD4HQLGgI+ZfLJ+uinFm8n/X5ewgE+EWVA2FFnimBu7i2kF70zNQQICXf03yVL6Fa3uSLVUnAmi+Xr7PLfBi3m2kYUuzx0yK7qLOFT0H5RDF5nVHPXhfUgf+G64/+JHaloPro/wkAAP//w8hMtckPAAA="; }
        }
    }
}
