// <auto-generated />
namespace CustomerManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class FirstDatabase : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203290140194_FirstDatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1YzW7jNhC+F+g7CDq1hzW9KbDYDZRdZJ2kCLpOglW697E0tomSlEpSgf1sPfSR+god6peSbMf5wbY3aTTzzcfh8OPY//z1d/RpI0XwgNrwTJ2FbyfTMECVZClXq7OwsMs378NPH3/8IbpM5Sb41vidOD+KVOYsXFubnzJmkjVKMBPJE52ZbGknSSYZpBk7mU7fs7dThgQRElYQRF8LZbnE8oVeZ5lKMLcFiHmWojC1nb7EJWpwAxJNDgmehbPC2EyinoOCFepJFREG54IDsYlRLJ9IbfrBUQvbpJT2kujZ7f02xzJ1l9X3Ir/fcNszkOlOZzlqu/2Kyzr2Og0D1o9jw8A2zItx6elJ2V9OwuCmEAIWggxLEAbDIH93GttM46+oUIPF9A6sRa1cLJb06zKc5u+Oq8QHNj1xlWCgVGbB0k6PiA9oXnFtrHts2MZWU+eEwRXfYPoF1cquW8Zz2DQWegyD3xWnRqMgqwvcscLDqb/Af5X5UgIX3z/t3TpTr7va6v1w1gs0ieZ51QzfOfdnru06hW2T+ILa/J7Lx0oXse74jg81aY0FTmemTlLriDPjxg7OdxUSox3IAOlNl6MSnUkrETvJtGk7bWOVuDUiyPaoYDSHPKeCe6pYW4K4lsQ38dMlT1YYLDE7lK9l22YiqaEyDb5SamJaigDtDSzAbcUslSO344rcJBvWeiixXembCPfcj+pfD5Pd+u0X84rWJ0k4y6Viy2mf9NfBcQIC9A7xnmWikGrfBXAo2tNUH8QzH4/ViaQP1VmPR6pFz4epTcdj1ArmY9Sm4zF6euQj9T4cj9dpjA/WWcdIERt0zLA92ag/B5f/sOEPycXQpc3eysZAHqL6qB4xSQ3PbuUSBlSiB566cxtvjUU5cQ6T+E8xE5zW2znQIeNLNPY++wPdVEjS8vxBrB0/jEnF/3Ua4275j85dT7zZR1OUegCdrEH/JGHz84sno5eh9aadl0H1Jpi9UM+cSl6EN5w0UtpY+9qTxviuPG7YODhrVGeWGC8yIl8x9aaUZ44iYw2JmP+bLaIN4KsOwv2CU5i4/ehAG59rtcyaetPqfEaNy2A75miBtgDOteVLSCx9TtCYcur8BqIo23KB6bW6LWxe2HNjUC5ET64jdjh/OW/1OUe3ZUeZ11gC0eSui27V54KLtOV9taOL9kC4fqlVhljR1E1wq22LdDO6OfcB1eW7wByV06h7lLkgMHOrYnjA/dwer2G/YtEFh5UG6VewstRMYqDMXgpK4Ed0+dxfDsz95/DxX72o5NGlEAAA"; }
        }
    }
}
